### PR TITLE
Update get-an-account.rst

### PR DESCRIPTION
**Pull request by DouglasLeeTucker**
Added some clarifying text to Step 2 of the Step-by-step instructions for obtaining and RSP account.

### CODE REVIEW

**Comment by DouglasLeeTucker** [comment]
OK, @MelissaGraham !  This is ready to review.  See Step 2 of https://rsp.lsst.io/v/PREOPS-5078/guides/getting-started/get-an-account.html#step-by-step .  Thanks!

**Comment by MelissaGraham** [comment]
Let's take off the "Home institutions not included on the the dropdown menu that are expecting to require numerous RSP accounts might consider reaching out to [CILogon](https://www.cilogon.org/home) (or [COmanage](https://comanage.nersc.gov/registry/)) directly to have their institutions’ names added." because that process is really not something individual users who are trying to get RSP accounts can even instigate. 

Recommend step 2 can just be this single bullet. It will format nicer with the image:

Choose an institution or identity provider with whom you have an established account, for example your home institute, ORCID, GitHub, or Google. Additional identities can be added later, if you have more than one.

**Review by MelissaGraham — CHANGES_REQUESTED** [review]
Could be shorter and simpler -- left suggestion in a comment.

**Comment by DouglasLeeTucker** [comment]
Updates applied!  Please see Step 2 of https://rsp.lsst.io/v/PREOPS-5078/guides/getting-started/get-an-account.html .  Thanks!

**Review by MelissaGraham — APPROVED** [review]

**Pull request merged**
